//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMMONConfig.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COMMONConfig.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Camera.
        /// </summary>
        public static string StringAddCamera {
            get {
                return ResourceManager.GetString("StringAddCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Lane.
        /// </summary>
        public static string StringAddLane {
            get {
                return ResourceManager.GetString("StringAddLane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Machine.
        /// </summary>
        public static string StringAddMachine {
            get {
                return ResourceManager.GetString("StringAddMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Network.
        /// </summary>
        public static string StringAddNetwork {
            get {
                return ResourceManager.GetString("StringAddNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Other.
        /// </summary>
        public static string StringAddOther {
            get {
                return ResourceManager.GetString("StringAddOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Router.
        /// </summary>
        public static string StringAddRouter {
            get {
                return ResourceManager.GetString("StringAddRouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add RPM.
        /// </summary>
        public static string StringAddRPM {
            get {
                return ResourceManager.GetString("StringAddRPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Server.
        /// </summary>
        public static string StringAddServer {
            get {
                return ResourceManager.GetString("StringAddServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Switch.
        /// </summary>
        public static string StringAddSwitch {
            get {
                return ResourceManager.GetString("StringAddSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Workstation.
        /// </summary>
        public static string StringAddWorkstation {
            get {
                return ResourceManager.GetString("StringAddWorkstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        public static string StringAlerts {
            get {
                return ResourceManager.GetString("StringAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Errors.
        /// </summary>
        public static string StringApplicationErrors {
            get {
                return ResourceManager.GetString("StringApplicationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string StringCamera {
            get {
                return ResourceManager.GetString("StringCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose....
        /// </summary>
        public static string StringChoose {
            get {
                return ResourceManager.GetString("StringChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collectors.
        /// </summary>
        public static string StringCollectors {
            get {
                return ResourceManager.GetString("StringCollectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string StringConfiguration {
            get {
                return ResourceManager.GetString("StringConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code.
        /// </summary>
        public static string StringCountryCode {
            get {
                return ResourceManager.GetString("StringCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Usage.
        /// </summary>
        public static string StringCpuUsage {
            get {
                return ResourceManager.GetString("StringCpuUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Usage Alert.
        /// </summary>
        public static string StringCpuUsageAlert {
            get {
                return ResourceManager.GetString("StringCpuUsageAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Usage Alert Counts.
        /// </summary>
        public static string StringCpuUsageAlertCount {
            get {
                return ResourceManager.GetString("StringCpuUsageAlertCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Low Disk Alert.
        /// </summary>
        public static string StringCriticalLowDiskAlert {
            get {
                return ResourceManager.GetString("StringCriticalLowDiskAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Low Memory Alert.
        /// </summary>
        public static string StringCriticalLowMemAlert {
            get {
                return ResourceManager.GetString("StringCriticalLowMemAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily File Location.
        /// </summary>
        public static string StringDailyFileLocation {
            get {
                return ResourceManager.GetString("StringDailyFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Size.
        /// </summary>
        public static string StringDatabaseSize {
            get {
                return ResourceManager.GetString("StringDatabaseSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Connection String.
        /// </summary>
        public static string StringDBConnection {
            get {
                return ResourceManager.GetString("StringDBConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Type.
        /// </summary>
        public static string StringDBType {
            get {
                return ResourceManager.GetString("StringDBType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string StringDelete {
            get {
                return ResourceManager.GetString("StringDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Days.
        /// </summary>
        public static string StringDeleteDays {
            get {
                return ResourceManager.GetString("StringDeleteDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string StringDevice {
            get {
                return ResourceManager.GetString("StringDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Settings.
        /// </summary>
        public static string StringDeviceSettings {
            get {
                return ResourceManager.GetString("StringDeviceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk.
        /// </summary>
        public static string StringDisk {
            get {
                return ResourceManager.GetString("StringDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk Speed.
        /// </summary>
        public static string StringDiskSpeed {
            get {
                return ResourceManager.GetString("StringDiskSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string StringEnabled {
            get {
                return ResourceManager.GetString("StringEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string StringEnglish {
            get {
                return ResourceManager.GetString("StringEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency (in minutes).
        /// </summary>
        public static string StringFrequency {
            get {
                return ResourceManager.GetString("StringFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic Device.
        /// </summary>
        public static string StringGenericDevice {
            get {
                return ResourceManager.GetString("StringGenericDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Frequency.
        /// </summary>
        public static string StringGlobalFrequency {
            get {
                return ResourceManager.GetString("StringGlobalFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string StringGroup {
            get {
                return ResourceManager.GetString("StringGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string StringGroups {
            get {
                return ResourceManager.GetString("StringGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Applications.
        /// </summary>
        public static string StringInstalledApplications {
            get {
                return ResourceManager.GetString("StringInstalledApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string StringIPAddress {
            get {
                return ResourceManager.GetString("StringIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lane.
        /// </summary>
        public static string StringLane {
            get {
                return ResourceManager.GetString("StringLane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lane Devices.
        /// </summary>
        public static string StringLaneDevices {
            get {
                return ResourceManager.GetString("StringLaneDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string StringLanguage {
            get {
                return ResourceManager.GetString("StringLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string StringLanguages {
            get {
                return ResourceManager.GetString("StringLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Boot Time.
        /// </summary>
        public static string StringLastBootTime {
            get {
                return ResourceManager.GetString("StringLastBootTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Group.
        /// </summary>
        public static string StringLeaveGroup {
            get {
                return ResourceManager.GetString("StringLeaveGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load from CSV file.
        /// </summary>
        public static string StringLoadCSV {
            get {
                return ResourceManager.GetString("StringLoadCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load from JSON file.
        /// </summary>
        public static string StringLoadJSON {
            get {
                return ResourceManager.GetString("StringLoadJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Reboot Alert.
        /// </summary>
        public static string StringLongRebootAlert {
            get {
                return ResourceManager.GetString("StringLongRebootAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Disk Alert.
        /// </summary>
        public static string StringLowDiskAlert {
            get {
                return ResourceManager.GetString("StringLowDiskAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Memory Alert.
        /// </summary>
        public static string StringLowMemAlert {
            get {
                return ResourceManager.GetString("StringLowMemAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory.
        /// </summary>
        public static string StringMemory {
            get {
                return ResourceManager.GetString("StringMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mongolian.
        /// </summary>
        public static string StringMongolian {
            get {
                return ResourceManager.GetString("StringMongolian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitored Drives.
        /// </summary>
        public static string StringMonitoredDrives {
            get {
                return ResourceManager.GetString("StringMonitoredDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string StringName {
            get {
                return ResourceManager.GetString("StringName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string StringNetwork {
            get {
                return ResourceManager.GetString("StringNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Devices.
        /// </summary>
        public static string StringNetworkDevices {
            get {
                return ResourceManager.GetString("StringNetworkDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Camera.
        /// </summary>
        public static string StringNewCamera {
            get {
                return ResourceManager.GetString("StringNewCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Machine.
        /// </summary>
        public static string StringNewMachine {
            get {
                return ResourceManager.GetString("StringNewMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New RPM.
        /// </summary>
        public static string StringNewRPM {
            get {
                return ResourceManager.GetString("StringNewRPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIC Usage.
        /// </summary>
        public static string StringNicUsage {
            get {
                return ResourceManager.GetString("StringNicUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string StringOK {
            get {
                return ResourceManager.GetString("StringOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string StringOther {
            get {
                return ResourceManager.GetString("StringOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string StringPassword {
            get {
                return ResourceManager.GetString("StringPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string StringPath {
            get {
                return ResourceManager.GetString("StringPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping.
        /// </summary>
        public static string StringPing {
            get {
                return ResourceManager.GetString("StringPing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes.
        /// </summary>
        public static string StringProcesses {
            get {
                return ResourceManager.GetString("StringProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Reboot Alert.
        /// </summary>
        public static string StringRecentRebootAlert {
            get {
                return ResourceManager.GetString("StringRecentRebootAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string StringRemove {
            get {
                return ResourceManager.GetString("StringRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string StringRestore {
            get {
                return ResourceManager.GetString("StringRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Router.
        /// </summary>
        public static string StringRouter {
            get {
                return ResourceManager.GetString("StringRouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPM.
        /// </summary>
        public static string StringRPM {
            get {
                return ResourceManager.GetString("StringRPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to CSV file.
        /// </summary>
        public static string StringSaveCSV {
            get {
                return ResourceManager.GetString("StringSaveCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to JSON file.
        /// </summary>
        public static string StringSaveJSON {
            get {
                return ResourceManager.GetString("StringSaveJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string StringServer {
            get {
                return ResourceManager.GetString("StringServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string StringServices {
            get {
                return ResourceManager.GetString("StringServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string StringSetting {
            get {
                return ResourceManager.GetString("StringSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string StringSettings {
            get {
                return ResourceManager.GetString("StringSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string StringSite {
            get {
                return ResourceManager.GetString("StringSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Name.
        /// </summary>
        public static string StringSiteName {
            get {
                return ResourceManager.GetString("StringSiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string StringSpanish {
            get {
                return ResourceManager.GetString("StringSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Updated.
        /// </summary>
        public static string StringSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("StringSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch.
        /// </summary>
        public static string StringSwitch {
            get {
                return ResourceManager.GetString("StringSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Errors.
        /// </summary>
        public static string StringSystemErrors {
            get {
                return ResourceManager.GetString("StringSystemErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Connection.
        /// </summary>
        public static string StringTestConnection {
            get {
                return ResourceManager.GetString("StringTestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMON Config.
        /// </summary>
        public static string StringTitle {
            get {
                return ResourceManager.GetString("StringTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string StringUnknown {
            get {
                return ResourceManager.GetString("StringUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Configuration.
        /// </summary>
        public static string StringUpdateConfiguration {
            get {
                return ResourceManager.GetString("StringUpdateConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string StringUpdated {
            get {
                return ResourceManager.GetString("StringUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPS.
        /// </summary>
        public static string StringUPS {
            get {
                return ResourceManager.GetString("StringUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uptime.
        /// </summary>
        public static string StringUptime {
            get {
                return ResourceManager.GetString("StringUptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string StringUsername {
            get {
                return ResourceManager.GetString("StringUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string StringValue {
            get {
                return ResourceManager.GetString("StringValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Devices.
        /// </summary>
        public static string StringWindowsDevices {
            get {
                return ResourceManager.GetString("StringWindowsDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workstation.
        /// </summary>
        public static string StringWorkstation {
            get {
                return ResourceManager.GetString("StringWorkstation", resourceCulture);
            }
        }
    }
}
