//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMMONConfig.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_test {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_test() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COMMONConfig.Localization.Resources.test", typeof(Resources_test).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringAddCamera {
            get {
                return ResourceManager.GetString("StringAddCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringAddCamera1 {
            get {
                return ResourceManager.GetString("StringAddCamera1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringAddLane {
            get {
                return ResourceManager.GetString("StringAddLane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringAddMachine {
            get {
                return ResourceManager.GetString("StringAddMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringAddMachine1 {
            get {
                return ResourceManager.GetString("StringAddMachine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringAddNetwork {
            get {
                return ResourceManager.GetString("StringAddNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringAddRouter {
            get {
                return ResourceManager.GetString("StringAddRouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringAddRPM {
            get {
                return ResourceManager.GetString("StringAddRPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringAddRPM1 {
            get {
                return ResourceManager.GetString("StringAddRPM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringAddServer {
            get {
                return ResourceManager.GetString("StringAddServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringAddSwitch {
            get {
                return ResourceManager.GetString("StringAddSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringAddWorkstation {
            get {
                return ResourceManager.GetString("StringAddWorkstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringApplicationErrors {
            get {
                return ResourceManager.GetString("StringApplicationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringCamera {
            get {
                return ResourceManager.GetString("StringCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringCamera1 {
            get {
                return ResourceManager.GetString("StringCamera1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringCollectors {
            get {
                return ResourceManager.GetString("StringCollectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringCollectors1 {
            get {
                return ResourceManager.GetString("StringCollectors1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringConfiguration {
            get {
                return ResourceManager.GetString("StringConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringConfiguration1 {
            get {
                return ResourceManager.GetString("StringConfiguration1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringCountryCode {
            get {
                return ResourceManager.GetString("StringCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringCpuUsage {
            get {
                return ResourceManager.GetString("StringCpuUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringCpuUsageAlert {
            get {
                return ResourceManager.GetString("StringCpuUsageAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringCpuUsageAlertCount {
            get {
                return ResourceManager.GetString("StringCpuUsageAlertCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringCriticalLowDiskAlert {
            get {
                return ResourceManager.GetString("StringCriticalLowDiskAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringCriticalLowMemAlert {
            get {
                return ResourceManager.GetString("StringCriticalLowMemAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringDailyFileLocation {
            get {
                return ResourceManager.GetString("StringDailyFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringDatabaseSize {
            get {
                return ResourceManager.GetString("StringDatabaseSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringDBConnection {
            get {
                return ResourceManager.GetString("StringDBConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringDBType {
            get {
                return ResourceManager.GetString("StringDBType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringDelete {
            get {
                return ResourceManager.GetString("StringDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringDelete1 {
            get {
                return ResourceManager.GetString("StringDelete1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringDeleteDays {
            get {
                return ResourceManager.GetString("StringDeleteDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringDevice {
            get {
                return ResourceManager.GetString("StringDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringDisk {
            get {
                return ResourceManager.GetString("StringDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringDiskSpeed {
            get {
                return ResourceManager.GetString("StringDiskSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringEnabled {
            get {
                return ResourceManager.GetString("StringEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringEnabled1 {
            get {
                return ResourceManager.GetString("StringEnabled1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringEnglish {
            get {
                return ResourceManager.GetString("StringEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringEnglish1 {
            get {
                return ResourceManager.GetString("StringEnglish1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringFrequency {
            get {
                return ResourceManager.GetString("StringFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringFrequency1 {
            get {
                return ResourceManager.GetString("StringFrequency1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringInstalledApplications {
            get {
                return ResourceManager.GetString("StringInstalledApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringIPAddress {
            get {
                return ResourceManager.GetString("StringIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringIPAddress1 {
            get {
                return ResourceManager.GetString("StringIPAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringLane {
            get {
                return ResourceManager.GetString("StringLane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringLanguages {
            get {
                return ResourceManager.GetString("StringLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringLanguages1 {
            get {
                return ResourceManager.GetString("StringLanguages1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringLastBootTime {
            get {
                return ResourceManager.GetString("StringLastBootTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringLongRebootAlert {
            get {
                return ResourceManager.GetString("StringLongRebootAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringLowDiskAlert {
            get {
                return ResourceManager.GetString("StringLowDiskAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringLowMemAlert {
            get {
                return ResourceManager.GetString("StringLowMemAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringMemory {
            get {
                return ResourceManager.GetString("StringMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringMongolian {
            get {
                return ResourceManager.GetString("StringMongolian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringMongolian1 {
            get {
                return ResourceManager.GetString("StringMongolian1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringName {
            get {
                return ResourceManager.GetString("StringName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringName1 {
            get {
                return ResourceManager.GetString("StringName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringNetwork {
            get {
                return ResourceManager.GetString("StringNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringNewCamera {
            get {
                return ResourceManager.GetString("StringNewCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringNewCamera1 {
            get {
                return ResourceManager.GetString("StringNewCamera1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringNewMachine {
            get {
                return ResourceManager.GetString("StringNewMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringNewMachine1 {
            get {
                return ResourceManager.GetString("StringNewMachine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringNewRPM {
            get {
                return ResourceManager.GetString("StringNewRPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringNewRPM1 {
            get {
                return ResourceManager.GetString("StringNewRPM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringNicUsage {
            get {
                return ResourceManager.GetString("StringNicUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringOK {
            get {
                return ResourceManager.GetString("StringOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringOK1 {
            get {
                return ResourceManager.GetString("StringOK1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringPassword {
            get {
                return ResourceManager.GetString("StringPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringPassword1 {
            get {
                return ResourceManager.GetString("StringPassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringPing {
            get {
                return ResourceManager.GetString("StringPing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringProcesses {
            get {
                return ResourceManager.GetString("StringProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringRecentRebootAlert {
            get {
                return ResourceManager.GetString("StringRecentRebootAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringRemove {
            get {
                return ResourceManager.GetString("StringRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringRemove1 {
            get {
                return ResourceManager.GetString("StringRemove1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringRestore {
            get {
                return ResourceManager.GetString("StringRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringRestore1 {
            get {
                return ResourceManager.GetString("StringRestore1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringRouter {
            get {
                return ResourceManager.GetString("StringRouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringRouter1 {
            get {
                return ResourceManager.GetString("StringRouter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringRPM {
            get {
                return ResourceManager.GetString("StringRPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringRPM1 {
            get {
                return ResourceManager.GetString("StringRPM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringServer {
            get {
                return ResourceManager.GetString("StringServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringServer1 {
            get {
                return ResourceManager.GetString("StringServer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringServices {
            get {
                return ResourceManager.GetString("StringServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringSetting {
            get {
                return ResourceManager.GetString("StringSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringSetting1 {
            get {
                return ResourceManager.GetString("StringSetting1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringSite {
            get {
                return ResourceManager.GetString("StringSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringSite1 {
            get {
                return ResourceManager.GetString("StringSite1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringSiteName {
            get {
                return ResourceManager.GetString("StringSiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringSiteName1 {
            get {
                return ResourceManager.GetString("StringSiteName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringSpanish {
            get {
                return ResourceManager.GetString("StringSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringSpanish1 {
            get {
                return ResourceManager.GetString("StringSpanish1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("StringSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringSuccessfullyUpdated1 {
            get {
                return ResourceManager.GetString("StringSuccessfullyUpdated1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringSwitch {
            get {
                return ResourceManager.GetString("StringSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringSwitch1 {
            get {
                return ResourceManager.GetString("StringSwitch1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringSystemErrors {
            get {
                return ResourceManager.GetString("StringSystemErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringTitle {
            get {
                return ResourceManager.GetString("StringTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringTitle1 {
            get {
                return ResourceManager.GetString("StringTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringUnknown {
            get {
                return ResourceManager.GetString("StringUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringUpdateConfiguration {
            get {
                return ResourceManager.GetString("StringUpdateConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringUpdateConfiguration1 {
            get {
                return ResourceManager.GetString("StringUpdateConfiguration1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringUpdated {
            get {
                return ResourceManager.GetString("StringUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringUpdated1 {
            get {
                return ResourceManager.GetString("StringUpdated1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringUPS {
            get {
                return ResourceManager.GetString("StringUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringUptime {
            get {
                return ResourceManager.GetString("StringUptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringUsername {
            get {
                return ResourceManager.GetString("StringUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringUsername1 {
            get {
                return ResourceManager.GetString("StringUsername1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringValue {
            get {
                return ResourceManager.GetString("StringValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringValue1 {
            get {
                return ResourceManager.GetString("StringValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringWorkstation {
            get {
                return ResourceManager.GetString("StringWorkstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string StringWorkstation1 {
            get {
                return ResourceManager.GetString("StringWorkstation1", resourceCulture);
            }
        }
    }
}
